### ISSUE TITLE
[Question] position text and filter icon

### ISSUE THREAD

**Issue by mrparag94** [DevExpress/DevExtreme#15459]
how I can position text at the end of the left side and the filter icon at the end of the right side. I mean I want the functionality of justify-between...

![image](https://user-images.githubusercontent.com/72906386/100573620-6e650f00-3302-11eb-899f-debff12986d6.png)

**Comment by NickMitrokhin** [comment]
Hi,

Use CSS to align HTML elements according to your requirements. You can find the required element using the DevTools of your browser. See [How to inspect CSS rules](https://supportcenter.devexpress.com/ticket/details/k18570/how-to-inspect-css-rules).

For your particular case, override CSS rules in the following manner:
```css
.dx-header-row .dx-column-indicators:last-child {
    float: right;
}
.dx-header-row .dx-column-indicators:first-child {
    float: left;
}
```
