### ISSUE TITLE
Make available LESS files in releases - To build for webpack with right fonts/icons folder path

### ISSUE THREAD

**Issue by pedrofurtado** [DevExpress/DevExtreme#6130]
Hey everyone!

Is it possible to make available the LESS files in future releases tags?

Because, by default, the CSS of devextreme get icons from "icons/***" relative path, just like this snippet below:

```css
@font-face {
  font-family: 'DXIcons';
  src: local("DevExtreme Generic Icons"), local("devextreme_generic_icons"), url(icons/dxicons.woff2) format('woff2'), url(icons/dxicons.woff) format('woff'), url(icons/dxicons.ttf) format('truetype');
  font-weight: normal;
  font-style: normal;
}
```

But when using webpack, the "icons/***" folder is resolved to my application root path, instead of devextreme node_modules folder path. Considering that my app root is "/home/user/app", the webpack try to resolve to "/home/user/app/icons/***".

Providing the LESS files I could change the variables available, to define the right folder (just like bootstrap, for example -> https://github.com/vuejs-templates/webpack/issues/166#issuecomment-227196456)

Thus, we can build the library automatically with webpack.

Thanks! :+1:
