### ISSUE TITLE
Incorrect "-webkit-gradient" usage

### ISSUE THREAD

**Issue by hakimio** [DevExpress/DevExtreme#6403]
### Steps to Reproduce:
1.  Run static analysis on devextreme material design theme css

### Results You Received:
Incorrect usage of "-webkit-gradient"
```css
.dx-colorview-palette-handle {
  background: -webkit-gradient(transparent 5px,  rgba(0, 0, 0, 0.2) 6px,  #fff 7px,  #fff 12px,  rgba(0, 0, 0, 0.2) 13px);
  /* ... */
}
```

### Results You Expected:
Correct usage of "-webkit-gradient" or not using it at all as there is no need for it anymore
```css
.dx-colorview-palette-handle {
  /* -webkit-gradient(<type>, <point> [, <radius>]?, <point> [, <radius>]? [, <stop>]*) */
  background: -webkit-gradient(radial, center center, 0, center center, 141, from(black), to(white), color-stop(25%, blue), color-stop(40%, green), color-stop(60%, red), color-stop(80%, purple));
  /* ... */
}
```

### Environment Details:
DevExtreme 18.2

-webkit-gradient is incorrectly used in [less mixin file](https://github.com/DevExpress/DevExtreme/blob/00a9888ea19b352ff3e2661747295a7952c383e3/styles/mixins.less#L30) on line 30.
